# aws_region      = "ap-south-1"
# environment     = "dev"
# cluster_name    = "jerney-eks-cluster"
# cluster_version = "1.35"
# vpc_cidr        = "10.0.0.0/16"

aws_region      = "ap-south-1"
environment     = "dev"
cluster_name    = "jerney-eks-cluster"
cluster_version = "1.34"
vpc_cidr        = "10.0.0.0/16"
